### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by nvx** [rfidreadermaker/proxmark3-max#1]
The proxmark3 source code is released under a GPL licence, as such publishing binaries like this repo is doing (or flashed on a device being sold) without the source code is in violation of the licence.

**Comment by team-orangeBlue** [comment]
Hey @rfidreadermaker we're not exactly ready to wait an indefinite amount of time.

The proxmark3 source code was licensed to you (and us) under the terms of the GNU GPL ver.3, which mandates you to...
* disclose the source code of the work, either by default or on demand
* state introduced changes
* provide a copy of the license so that users of your work know their rights
So far you have complied with one point out of the three above, notably mentions of changes, and haven't introduced any changes or commits to your repository since this issue was made.

A person willing to is in their rights to file for takedown.

**Comment by rfidreadermaker** [comment]
GUl is a third-party software that is not modified through the underlying source code of Proxmark, nordoes it follow open source aareements, The software is aifted to Max users and is not used forcommercial purposes，Bottom level source code address: https://github.com/RfidResearchGroup/proxmark3

**Comment by nvx** [comment]
> GUl is a third-party software that is not modified through the underlying source code of Proxmark, nordoes it follow open source aareements, The software is aifted to Max users and is not used forcommercial purposes，Bottom level source code address: https://github.com/RfidResearchGroup/proxmark3

I wasn't referring to the GUI code, I specifically meant the modified firmware and proxmark3 client versions which are modified from the RfidReararchGroup repo you linked and are protected by GPL.

Please reopen this issue @rfidreadermaker as it's not resolved.

**Comment by nvx** [comment]
@rfidreadermaker hello?
